M48
; DRILL file {KiCad 9.0.2-9.0.2-0~ubuntu24.04.1} date 2025-07-07T23:28:06+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-07T23:28:06+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2-9.0.2-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X3.85Y-1.55
X3.85Y-3.55
X5.9Y-1.55
X5.9Y-3.55
M30
